### PR TITLE
Fix: make font bg transparent (#2)

### PR DESCRIPTION
**Pull request by tenuki**
Fix: make font bg transparent (#2)

### CODE REVIEW

**Comment by facundobatista** [comment]
Thanks for this!!! I've found several issues, though. I've been trying to fix it, but as I'm not fully understanding the changes in this PR, I couldn't improve it.

On one hand, it crashes. It does not happen always, but I reproduced it 100% if I start a game, quit in the middle, it shows me highscores, etc, and then:

```
  File "/home/facundo/devel/reps/typuspocus/typuspocus/game.py", line 943, in paint
    sf = hollow.textOutline(font2, self.name, (255, 254, 232), (0, 0, 0))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facundo/devel/reps/typuspocus/typuspocus/hollow.py", line 30, in textOutline
    base.set_palette_at(1, notcolor)
pygame.error: Surface colors are not indexed
```

But also, some texts looks very weird.

See for example the scores during the game:

malfont1

Also this message:

malf2

And even the spell chars (not that bad, but weird effect is there):

malfont

In comparison see these details of old captures (currently in `media` dir):

fontok2
fontok1

**Review by facundobatista — CHANGES_REQUESTED** [review]
(commented in discussion)

**Comment by tenuki** [comment]
> Thanks for this!!! I've found several issues, though. I've been trying to fix it, but as I'm not fully understanding the changes in this PR, I couldn't improve it.

I'll tell you what I did.

First I've changed the code to fix the issue, the diff was (copying the diff because of wrong line ending making it difficult to check in gh directly):

```
 import pygame
+from pygame.color import Color
 from pygame.locals import KEYDOWN, QUIT, MOUSEBUTTONDOWN, K_s
 
 
+Transparent = Color(0, 0, 0, a=0)
+Transparent.a = 0  # ^ above line seems not to set the alpha!
+
+
 def textOutline(font, message, fontcolor, outlinecolor):
     borde = font.render(message, 1, outlinecolor)
     base = font.render(message, 1, fontcolor)
     img = pygame.Surface(base.get_rect().inflate(2, 2).size, 0, base).convert_alpha()
+    img.fill(Transparent)
     for x in 0, 2:
         for y in 0, 2:
             img.blit(borde, (x, y))
```  

Then, after finding that works, I wen't to the site linked in the comment in the sources where the original effect comes from, and took that code and integrated it back. The new code was more complex but optimized. I hadn't paid attention to the detail.  Certainly the original code produces better output.

I turned the version back to the first without the improvements, and I think its code is understandable and the works as expected.

> On one hand, it crashes. It does not happen always, but I reproduced it 100% if I start a game, quit in the middle, it shows me highscores, etc, and then:
> 
> ```
>   File "/home/facundo/devel/reps/typuspocus/typuspocus/game.py", line 943, in paint
>     sf = hollow.textOutline(font2, self.name, (255, 254, 232), (0, 0, 0))
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/facundo/devel/reps/typuspocus/typuspocus/hollow.py", line 30, in textOutline
>     base.set_palette_at(1, notcolor)
> pygame.error: Surface colors are not indexed
> ```

Haven´t reproduced this issue. Let me know if this happens again!

**Review by facundobatista — APPROVED** [review]
Maravilloso!!

**Pull request merged**
